language: node_js
matrix:
  include:
    - node_js: "12"
    - node_js: "13"
      env: "NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/nightly"
install:
  - sudo apt-get update -qq
  - sudo apt-get install -q python3
script:
  - python3 tools/test.py -j 4 parallel sequential